export { crearDeck } from './creardeck'
export { pedirCarta } from './pedir-carta'
export { valorCarta } from './valor-carta'
export { turnoComputadora } from './turno-computadora'
export { crearCartaHtml } from './crear-carta-html'